name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  style:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
