name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: dprint-check-action
      - uses: actions/checkout@v2
      - uses: dprint/check@v2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
