name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
    tags:
    - '*'
  push:
    tags:
    - '*'

jobs:
  style:
    name: CI
    runs-on: ubuntu-latest
  

    steps:
    steps:
  # check out the repository
      - uses: actions/checkout@v3
        # setup node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
        # cache the node_modules folder
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/dprint
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/dprint.json') }}
        # install the packages in the package.json
      - run: npm ci
        # verify formatting
      - name: dprint w/ dprint-plugin-prettier
        run: npm run fmt-check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
