name: CI

on:
  pull_request:
    branches: [dprint]
  push:
    branches: [dprint]
    tags:
    - '*'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3 s
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm ci
    - name: prettier
      run: npm run prettier
    - name: dprint w/ dprint-plugin-prettier
      run: npm run dprint